config/routes.rb
Rails.application.routes.draw do
  resources :lists do
    resources :items
  end
  resource :sessions
  resources :users

  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  get 'signup', to: 'users#new', as: 'signup'

  patch 'lists/:list_id/items/:id/add', to: 'items#add'
  patch 'lists/:list_id/items/:id/remove', to: 'items#remove'
  patch 'lists/:list_id/items/:id/check', to: 'items#check'
  patch 'lists/:list_id/items/:id/uncheck', to: 'items#uncheck'

  root 'lists#index'
end

app/models/list.rb
class List < ApplicationRecord
  validates :name, :presence => true
  has_many :items
  has_many :authzs
  has_many :users, through: :authzs
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_list, only: %i[ show edit update destroy ]
  before_action :authorize_user_list!, only: %i[ show edit update destroy ]

  # GET /lists or /lists.json
  def index
    @lists = current_user.lists
  end

  # GET /lists/1 or /lists/1.json
  def show
  end

  # GET /lists/new
  def new
    @list = List.new
  end

  # GET /lists/1/edit
  def edit
  end

  # POST /lists or /lists.json
  def create
    @list = List.new(list_params)
    @authz = Authz.new
    @list.authzs << @authz
    @current_user.authzs << @authz

    respond_to do |format|
      begin
        ActiveRecord::Base.transaction do
          @list.save!
          @current_user.save!
        end
        format.html { redirect_to list_url(@list), notice: "List was successfully created." }
        format.json { render :show, status: :created, location: @list }
      rescue => e
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lists/1 or /lists/1.json
  def update
    respond_to do |format|
      if @list.update(list_params)
        format.html { redirect_to list_url(@list), notice: "List was successfully updated." }
        format.json { render :show, status: :ok, location: @list }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lists/1 or /lists/1.json
  def destroy
    @list.destroy

    respond_to do |format|
      format.html { redirect_to lists_url, notice: "List was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_list
      @list = List.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def list_params
      params.require(:list).permit(:name)
    end
end

app/helpers/lists_helper.rb
module ListsHelper
  def order
    case params[:order]
    when "name"
      "by name"
    when "location"
      "by location"
    else
      "by last used"
    end
  end

  def items_grouped_and_ordered(list, my_order=nil, filter_removed=nil)
    my_order ||= order
    items = list.items
    if filter_removed
      items = items.where(removed: nil)
    end
    case my_order
    when "by name"
      { "": items.order(:name) }
    when "by location"
      items.order(:location, :name).group_by { |i| i.location }
    when "by last used"
      { "": items.order('updated_at DESC') }
    end
  end
end

app/views/lists/_form.html.erb
<%= form_with(model: list) do |form| %>
  <% if list.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(list.errors.count, "error") %> prohibited this list from being saved:</h2>

      <ul>
        <% list.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <br>
  
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/lists/_list.html.erb
<table>
  <tbody>
    <% items_grouped_and_ordered(@list, 'by location', true).each_with_index do |(location,items)| %>
    <tr><td style="text-align:center"><span style="text-decoration: underline black 2px;"><strong>
	    <%= location %>
    </strong></span></td></tr>
    <% items.each do |item| %>
    <tr>
      <td>☐ <%= item.name %></td>
      <td style="padding: 0 0 0 50px"><%= link_to 'Edit', edit_list_item_path(@list, item) %></td>
      <td style="padding: 0 0 0 20px"><%= button_to 'Remove', list_item_path(@list, item) + '/remove', method: :patch  %></td>
    </tr>
    <% end %>
    <% end %>
  </tbody>
</table>

app/views/lists/edit.html.erb
<h1>Editing list</h1>

<%= render "form", list: @list %>

<br>

<div>
  <%= link_to "Cancel", list_path(@list) %></li>
</div>

<h2>Actions</h2>

<ul>
  <li><%= button_to "Delete this list",  @list, method: :delete %></li>
</ul>

app/views/lists/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Lists</h1>

<ul>
  <% @lists.each do |list| %>
  <li><%= link_to list.name, list %></li>
  <% end %>
</ul>

<h2>Actions</h2>

<ul>
  <li><%= link_to "New list", new_list_path %></li>
</ul>

app/views/lists/new.html.erb
<h1>New list</h1>

<%= render "form", list: @list %>

<br>

<div>
  <%= link_to "Cancel", lists_path %>
</div>

app/views/lists/show.html.erb
<h1><%= @list.name %></h1>

<%= link_to "Add items from master list", list_items_path(@list, order: params[:order]) %>

<br>
<br>

<%= render @list %>

<br>

<%= link_to "Add items from master list", list_items_path(@list, order: params[:order]) %>

<h2>Actions</h2>

<ul>
  <li><%= link_to "Back to lists", lists_path %></li>
  <li><%= link_to "Edit this list", edit_list_path(@list) %></li>
</ul>