config/routes.rb
Rails.application.routes.draw do
  resources :lists do
    resources :items
  end
  resource :sessions
  resources :users

  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  get 'signup', to: 'users#new', as: 'signup'

  patch 'lists/:list_id/items/:id/add', to: 'items#add'
  patch 'lists/:list_id/items/:id/remove', to: 'items#remove'
  patch 'lists/:list_id/items/:id/check', to: 'items#check'
  patch 'lists/:list_id/items/:id/uncheck', to: 'items#uncheck'

  root 'lists#index'
end

app/models/item.rb
class Item < ApplicationRecord
  validates :name, :presence => true
  belongs_to :list
end

app/controllers/concerns/items.rb
module Items
  def get_list
    @list = List.find(params[:list_id])
  end

  def set_item
    @item = @list.items.find(params[:id])
  end

  def normalize_item(item)
    item.name = item.name.strip
    item.location = item.location.strip
  end

  def deduplicate(list, item)
    items = list.items.where(name: item.name)
    if items.empty?
      return item
    else
      i = items[0]
      i.location = item.location unless item.location.empty? # Keep the new category
      return items[0]
    end
  end

  def create_item_and_redirect_to(url)

    @item = @list.items.build(item_params)
    normalize_item(@item)
    @item = deduplicate(@list, @item)
    @item.removed = nil

    respond_to do |format|
      if @item.save
        format.html { redirect_to url, notice: "#{@item.name} was added." }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  def add_item_and_redirect_back
    @item.removed = nil
    @item.save!
    redirect_back fallback_location: root_path, notice: "#{@item.name} was added."
  end

  def remove_item_and_redirect_back
    @item.removed = true
    @item.save!
    redirect_back fallback_location: root_path, notice: "#{@item.name} was removed."
  end

  def check_item_and_redirect_back
    @item.checked = true
    @item.save!
    redirect_back fallback_location: root_path
  end

  def uncheck_item_and_redirect_back
    @item.checked = nil
    @item.save!
    redirect_back fallback_location: root_path
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  include Items

  before_action :authenticate_user!
  before_action :get_list
  before_action :authorize_user_list!
  before_action :set_item, only: %i[ show edit update destroy add remove check uncheck ]

  # GET /lists/1/items
  def index
    @items = @list.items
  end

  # GET /lists/1/items/1
  def show
  end

  # GET /lists/1/items/new
  def new
    @item = @list.items.build
  end

  # GET /lists/1/items/1/edit
  def edit
  end

  # POST /lists/1/items
  def create
    create_item_and_redirect_to list_url(@list)
  end

  # PATCH/PUT /lists/1/items/1
  def update
    respond_to do |format|
      if @item.update(item_params)
        normalize_item(@item)
        @item.save!
        format.html { redirect_to list_url(@list), notice: "#{@item.name} was updated." }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH /lists/1/items/1/add
  def add
    add_item_and_redirect_back
  end

  # PATCH /lists/1/items/1/remove
  def remove
    remove_item_and_redirect_back
  end

  # PATCH /lists/1/items/1/check
  def check
    check_item_and_redirect_back
  end

  # PATCH /lists/1/items/1/uncheck
  def uncheck
    uncheck_item_and_redirect_back
  end
  
  # DELETE /lists/1/items/1
  def destroy
    @item.destroy

    respond_to do |format|
      format.html { redirect_back fallback_location: root_path, notice: "#{@item.name} was deleted." }
      format.json { head :no_content }
    end
  end

  private
    # Only allow a list of trusted parameters through.
    def item_params
      params.require(:item).permit(:name, :location, :checked, :list_id)
    end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<%= form_with(model: [@list, item]) do |form| %>

  <% if item.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
        <% item.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name, list: "existing_items" %>
  </div>

  <datalist id="existing_items">
    <% @list.items.order(:name).each do |i| %>
    <option value="<%= i.name %>">
    <% end %>
  </datalist>

  <div>
    <%= form.label :location, style: "display: block" %>
    <%= form.text_field :location, list: "existing_locations" %>
  </div>

  <datalist id="existing_locations">
    <% @list.items.order(:location).each do |i| %>
    <option value="<%= i.location %>">
    <% end %>
  </datalist>
  
  <br>
  
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/items/_item.html.erb
<div id="<%= dom_id item %>">
  <p>
    <strong>Name:</strong>
    <%= item.name %>
  </p>

  <p>
    <strong>Location:</strong>
    <%= item.location %>
  </p>
  
  <p>
    <strong>Checked:</strong>
    <%= item.checked %>
  </p>

  <p>
    <strong>List:</strong>
    <%= item.list_id %>
  </p>

</div>

app/views/items/edit.html.erb
<h1>Editing item</h1>

<%= render "form", item: @item %>

<br>

<div>
  <%= link_to "Cancel", list_path(@list) %>
</div>

app/views/items/index.html.erb
<h1><%= @list.name + ' master list (' + order + ')' %></h1>

<%= link_to "Create / add item", new_list_item_path(@list, order: params[:order]) %>
<br>
<%= link_to "Back to current list", list_path(@list, order: params[:order]) %>

<br>
<br>

<table>
  <tbody>
    <% items_grouped_and_ordered(@list).each_with_index do |(location,items)| %>
    <tr><td style="text-align:center"><span style="text-decoration: underline black 2px;"><strong>
	    <%= location %>
    </strong></span></td></tr>
    <% items.each do |item| %>
    <tr>
      <td>☐ <%= item.name %></td>
      <td style="padding: 0 0 0 50px"><%= link_to 'Edit', edit_list_item_path(@list, item) %></td>
      <% if item.removed %>
      <td style="padding: 0 0 0 20px"><%= button_to 'Add', list_item_path(@list, item) + '/add', method: :patch %></td>
      <% else %>
      <td style="padding: 0 0 0 20px"><%= button_to 'Remove', list_item_path(@list, item) + '/remove', method: :patch %></td>
      <% end %>
      <td style="padding: 0 0 0 20px"><%= button_to 'Delete', list_item_path(@list, item), method: :delete %></td>
    </tr>
    <% end %>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to "Create / add item", new_list_item_path(@list, order: params[:order]) %>
<br>
<%= link_to "Back to current list", list_path(@list, order: params[:order]) %>

<h2>Order</h2>

<ul>
  <li><%= link_to "by name", list_items_path(@list, order: "name") %></li>
  <li><%= link_to "by location", list_items_path(@list, order: "location") %></li>
  <li><%= link_to "by last used", list_items_path(@list, order: "last_updated") %></li>
</ul>

app/views/items/new.html.erb
<h1><%= @list.name %></h1>

<%= render "form", item: @item %>

<br>

<div>
  <%= link_to "Cancel", list_path(@list) %>
</div>

app/views/items/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @item %>

<div>
  <%= link_to "Edit this item", edit_list_item_path(@list, @item) %> |
  <%= link_to "Back to items", list_items_path(@list) %>

  <%= button_to "Destroy this item", list_item_path(@list, @item), method: :delete %>
</div>